### ISSUE TITLE
Wider Ender Chests shifts vanilla block ids

### ISSUE THREAD

**Issue by SuperMartijn642** [Craft1x/WiderEnderChests#1]
Wider Ender Chests registers blocks through a mixin into the `Blocks` class:
https://github.com/Craft1x/WiderEnderChests/blob/f7d76f7c46894f876d5852c7b1263b024bf85f8b/fabric/src/main/java/com/craftix/wider_ender_chests/shared/mixin/BlocksMix.java#L20-L32

As the blocks are registered at the head of `<clinit>` in the `Blocks` class, they get registered before vanilla's blocks. This results in the blocks from Wider Ender Chests getting assigned ids starting at 0.

Usually the 0 id is assigned to the air block and it seems vanilla also makes this assumption. The `Block#getId` method will return 0 in case the given argument is `null` or the given state is not registered.
Vanilla also uses the 0 id when serializing `EntityDataSerializers#OPTIONAL_BLOCK_STATE` to indicate that an optional blockstate argument is absent.
These were the main two cases I could find in vanilla code, so not entirely sure if this is valid assumption. Still, I don't think this is desirable.

Although on Fabric  you are of course free to register things as you like, I think a better solution would be to simply register things when the mod is initialized as most mods do and is recommended on the Fabric wiki.
On Forge and NeoForge, things should be registered during the relevant registry events. Registries are intentionally locked outside those events and I believe bypassing this by registering things with a mixin into the initialization of vanilla classes is (probably unintentionally) bypassing this.

Anyways, I only noticed this because of https://github.com/SuperMartijn642/MovingElevators/issues/230 where I had used 0 to indicate air.
So yeah, not sure if this causing any real issues, but I assume it probably isn't done intentionally and likely just an unintended effect. If nothing else, just changing the `Blocks` mixin's injection point from `HEAD` to `TAIL` would mean vanilla ids remain starting at 0.

**Comment by Craft1x** [comment]
Thanks for reporting the issue!

**Comment by Craft1x** [comment]
I think you could consider saving the blockstates similar to how the Enderman does it:
`compoundTag.put("carriedBlockState", NbtUtils.writeBlockState(blockState));`
`blockState = NbtUtils.readBlockState(this.level().holderLookup(Registries.BLOCK), compoundTag.getCompound("carriedBlockState"));`

Blockstate ids can be inconsistent and may change when mods are replaced:
https://streamable.com/enjs97

**Comment by SuperMartijn642** [comment]
Ah the original issue was only related to sending data from server to client. Didn't even realize it also uses blockstate ids to save to disk. It's been a while since I wrote this code and likely just didn't realize at the time.
Thank you, I will get to updating that then
